feature/21
whiteboardfederal/resumaker-server pull request #33
Opened 2020-02-25 00:55 UTC by jghorton14

Added swagger to Employee, Education, and work history #21

2020-02-25 01:12 UTC, jghorton14 commented
I think i did this correctly... I cant for the life of me figure out these stupid .class modifications.

2020-03-01 23:58 UTC, DougWBF requested changes
Don't want to push the .class files to git

2020-03-02 01:50 UTC, jghorton14 commented
Removed class files

2020-03-09 04:42 UTC, DougWBF approved these changes

2020-03-09 21:15 UTC, merged