RefCertification files and change to DbInitializer
whiteboardfederal/resumaker-server pull request #37
Opened 2020-02-28 04:25 UTC by tbui16

2020-03-01 23:56 UTC, DougWBF requested changes

2020-03-01 23:56 UTC, DougWBF commented on src/main/java/com/whiteboardfederal/resumaker/controller/RefCertificationController.java
> +  RefCertification create(@RequestBody RefCertification p) {
Change variable name to something meaningful, throughout the entire controller

2020-03-02 01:24 UTC, vivle requested changes
Remove comment in RefCertification.java

2020-03-02 01:24 UTC, vivle commented on src/main/java/com/whiteboardfederal/resumaker/model/RefCertification.java
> +//What are these imports?
Remove comments, don't need these for your entity.

2020-03-13 02:27 UTC, merged